[project]
name = "scheduler-v3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "rich>=14.1.0",
    "uvicorn>=0.35.0",
    "httpx>=0.27.0",
    "black>=25.1.0",
]
